---CREATE TABLE SALES DATA---

CREATE TABLE SALES_DATA(
ORDERNUMBER NUMERIC,
QUANTITYORDERED NUMERIC,
PRICEEACH float8,
ORDERLINENUMBER NUMERIC,
SALES FLOAT8,
ORDERSATE DATE,
STATUS VARCHAR,
QTRID NUMERIC,
MONTHID NUMERIC,
YEAR INT,
PRODUCTLINE VARCHAR,
MSRP NUMERIC,
PRODUCTCODE VARCHAR,
CUSTOMERNAME VARCHAR,
PHONE VARCHAR,
ADDRESSLINE1 VARCHAR,
ADDRESSLINE2 VARCHAR,
CITY VARCHAR,
STATE VARCHAR,
POSTALCODE VARCHAR,
COUNTRY VARCHAR,
TERRITORY VARCHAR,
CONTACTLASTNAME VARCHAR,
CONTACTFIRSTNAME VARCHAR,
DEALSIZE VARCHAR);

---IMPORT TABLE SALES_DATA---
COPY SALES_DATA FROM 'C:\Users\Public\Documents\SALES_DATA.csv' DELIMITER ','CSV HEADER;
SELECT * FROM SALES_DATA;
---CONCATENATE CONTACTFIRSTNAME AND CONTACTLAST NAME AS CONTACTNAME---
SELECT CONTACTLASTNAME || CONTACTFIRSTNAME AS CONTACTNAME FROM SALES_DATA;


SELECT * FROM SALES_DATA;
---SUM OF SALES FOR USA---
SELECT COUNTRY, SUM(SALES) FROM SALES_DATA 
WHERE COUNTRY='USA'
GROUP BY COUNTRY
ORDER BY SUM(SALES) DESC;

---TOP 5 SALES BY COUNTRY---
SELECT COUNTRY, SUM(SALES) FROM SALES_DATA
GROUP BY COUNTRY
ORDER BY SUM(SALES) DESC
LIMIT 5;

----COUNTRIES WITH SALES STATUS 'SHIPPED'---

SELECT COUNTRY,STATUS FROM SALES_DATA
WHERE STATUS='Shipped';
----NUMBER OF GOODS WHOSE STATUS ='SHIPPED'----
SELECT COUNTRY, COUNT(STATUS) FROM SALES_DATA
WHERE STATUS='Shipped' AND COUNTRY='USA'
GROUP BY COUNTRY;

---THE COUNTRIES AND CITIES WHERE CLASSIC CARS ARE SOLD---

SELECT DISTINCT COUNTRY,CITY,PRODUCTLINE FROM SALES_DATA 
WHERE PRODUCTLINE='Classic Cars';

---TOTAL OF DIFFERENT STATUS OF AUTOMOBILE---
SELECT SUM(SAlES),STATUS FROM SALES_DATA
WHERE STATUS
IN('Cancelled','On Hold','Shipped','Resolved','In Process','Disputed')
GROUP BY STATUS
ORDER BY SUM(SALES) DESC;



